name: Deploy EC2 with Terraform

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform Action'
        required: true
        type: choice
        options:
          - plan
          - plan-destroy
          - apply
          - destroy
        default: 'plan'
jobs:
  terraform-ec2:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init (uses S3 backend)
      run: terraform init
      working-directory: terraform-ec2

    - name: Terraform Validate
      run: terraform validate
      working-directory: terraform-ec2

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: terraform-ec2

    - name: Terraform Plan Destroy
      if: github.event.inputs.terraform_action == 'plan-destroy'
      run: terraform plan -destroy -out=tfplan
      working-directory: terraform-ec2

    - name: Terraform Apply
      if: github.event.inputs.terraform_action == 'apply'
      run: terraform apply -auto-approve tfplan
      working-directory: terraform-ec2

    - name: Terraform Destroy
      if: github.event.inputs.terraform_action == 'destroy'
      run: terraform destroy -auto-approve
      working-directory: terraform-ec2   
