name: Deploy EC2 with Terraform

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform Action'
        required: true
        type: choice
        options:
          - plan
          - plan-destroy
          - apply
          
        
env:
  AWS_REGION: us-east-1  # Change this to your AWS region

jobs:
  terraform:
    name: Apply Terraform Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0  # Specify the Terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # - name: Initialize Terraform
      #   run: terraform init \
      #         -backend-config="key=terraform.tfstate" \
      #         -backend-config="bucket=madhutfstate" \
      #         -backend-config="region=us-east-1"
        

      # - name: Validate Terraform
      #   run: terraform validate

      - name: Terraform Plan
        if: inputs.terraform_action == 'plan'
        run: |
          terraform init \
              -backend-config="key=terraform.tfstate" \
              -backend-config="bucket=madhutfstate" \
              -backend-config="region=us-east-1"

          terraform validate

          terraform plan -out=tfplan 

      - name: Terraform Plan Destroy
        if: inputs.terraform_action == 'plan-destroy'
        run: |
          terraform init \
              -backend-config="key=terraform.tfstate" \
              -backend-config="bucket=madhutfstate" \
              -backend-config="region=us-east-1"

          terraform validate
        
          terraform plan -destroy -out=tfplan

      - name: Terraform Apply
        if: inputs.terraform_action == 'apply'
        run: 
          terraform init \
              -backend-config="key=terraform.tfstate" \
              -backend-config="bucket=madhutfstate" \
              -backend-config="region=us-east-1"

          terraform validate
        
          terraform apply -auto-approve tfplan


      